window.esdocSearchIndex = [
  [
    "data-scheme/source/scheme/index.js~email",
    "variable/index.html#static-variable-Email",
    "<span>Email</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "variable"
  ],
  [
    "data-scheme/source/hook/index.js~http",
    "function/index.html#static-function-HTTP",
    "<span>HTTP</span> <span class=\"search-result-import-path\">data-scheme/source/hook/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/scheme/index.js~http_url",
    "function/index.html#static-function-HTTP_URL",
    "<span>HTTP_URL</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/scheme/index.js~ipa",
    "function/index.html#static-function-IPA",
    "<span>IPA</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/scheme/index.js~ipv4",
    "function/index.html#static-function-IPv4",
    "<span>IPv4</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/scheme/index.js~ipv6",
    "function/index.html#static-function-IPv6",
    "<span>IPv6</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/model.js~model",
    "class/source/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">data-scheme/source/Model.js</span>",
    "class"
  ],
  [
    "data-scheme/source/scheme/index.js~phone",
    "variable/index.html#static-variable-Phone",
    "<span>Phone</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "variable"
  ],
  [
    "data-scheme/source/scheme/index.js~range",
    "function/index.html#static-function-Range",
    "<span>Range</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/scheme/index.js~uri",
    "variable/index.html#static-variable-URI",
    "<span>URI</span> <span class=\"search-result-import-path\">data-scheme/source/scheme/index.js</span>",
    "variable"
  ],
  [
    "data-scheme/source/validator.js~is",
    "function/index.html#static-function-is",
    "<span>is</span> <span class=\"search-result-import-path\">data-scheme/source/validator.js</span>",
    "function"
  ],
  [
    "data-scheme/source/utility/index.js~isclass",
    "function/index.html#static-function-isClass",
    "<span>isClass</span> <span class=\"search-result-import-path\">data-scheme/source/utility/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/hook/index.js~listen",
    "function/index.html#static-function-listen",
    "<span>listen</span> <span class=\"search-result-import-path\">data-scheme/source/hook/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/model.js~mapgetter",
    "function/index.html#static-function-mapGetter",
    "<span>mapGetter</span> <span class=\"search-result-import-path\">data-scheme/source/Model.js</span>",
    "function"
  ],
  [
    "data-scheme/source/hook/index.js~trigger",
    "function/index.html#static-function-trigger",
    "<span>trigger</span> <span class=\"search-result-import-path\">data-scheme/source/hook/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/utility/index.js~typeof",
    "function/index.html#static-function-typeOf",
    "<span>typeOf</span> <span class=\"search-result-import-path\">data-scheme/source/utility/index.js</span>",
    "function"
  ],
  [
    "data-scheme/source/utility/index.js~walkprototype",
    "function/index.html#static-function-walkPrototype",
    "<span>walkPrototype</span> <span class=\"search-result-import-path\">data-scheme/source/utility/index.js</span>",
    "function"
  ],
  [
    "",
    "test-file/test/Model.js.html#lineNumber14",
    "Scheme class",
    "test"
  ],
  [
    "is source/validator.js~is,is",
    "test-file/test/Model.js.html#lineNumber55",
    "Scheme class Basic Data type",
    "test"
  ],
  [
    "http listen trigger source/hook/index.js~http,http source/hook/index.js~listen,listen source/hook/index.js~trigger,trigger",
    "test-file/test/Model.js.html#lineNumber101",
    "Scheme class Decorator Hook",
    "test"
  ],
  [
    "is model#foreach source/validator.js~is,is source/model.js~model#foreach,model#foreach",
    "test-file/test/Model.js.html#lineNumber40",
    "Scheme class Default value",
    "test"
  ],
  [
    "mapgetter source/model.js~mapgetter,mapgetter",
    "test-file/test/Model.js.html#lineNumber18",
    "Scheme class Getter / Setter pairs",
    "test"
  ],
  [
    "model#foreach is source/model.js~model#foreach,model#foreach source/validator.js~is,is",
    "test-file/test/Model.js.html#lineNumber78",
    "Scheme class Inherited & Nested Model",
    "test"
  ],
  [
    "range source/scheme/index.js~range,range",
    "test-file/test/Model.js.html#lineNumber65",
    "Scheme class Number range",
    "test"
  ],
  [
    "model#observe model#set source/model.js~model#observe,model#observe source/model.js~model#set,model#set",
    "test-file/test/Model.js.html#lineNumber125",
    "Scheme class Observe key-value changed",
    "test"
  ],
  [
    "is source/validator.js~is,is",
    "test-file/test/Model.js.html#lineNumber29",
    "Scheme class Required field",
    "test"
  ],
  [
    "",
    "test-file/test/scheme.js.html#lineNumber7",
    "Scheme validator",
    "test"
  ],
  [
    "http_url source/scheme/index.js~http_url,http_url",
    "test-file/test/scheme.js.html#lineNumber34",
    "Scheme validator HTTP URL",
    "test"
  ],
  [
    "ipv4 source/scheme/index.js~ipv4,ipv4",
    "test-file/test/scheme.js.html#lineNumber11",
    "Scheme validator IP v4",
    "test"
  ],
  [
    "ipv6 source/scheme/index.js~ipv6,ipv6",
    "test-file/test/scheme.js.html#lineNumber20",
    "Scheme validator IP v6",
    "test"
  ],
  [
    "source/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "source/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "source/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "source/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "source/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "source/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "source/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "source/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "source/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "source/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "source/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "source/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "source/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "source/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "source/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "source/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "source/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "source/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "source/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "source/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "source/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "source/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "source/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "source/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "source/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "source/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "source/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "source/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "source/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "source/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "source/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "source/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "source/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "source/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "source/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "source/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~String",
    "external"
  ],
  [
    "source/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "source/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "source/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "source/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "source/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "source/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "source/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "source/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "source/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "source/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "source/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "source/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "source/.external-ecmascript.js~null",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~string",
    "external"
  ],
  [
    "source/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "source/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "source/model.js",
    "file/source/Model.js.html",
    "source/Model.js",
    "file"
  ],
  [
    "source/model.js~model#[model_observer]",
    "class/source/Model.js~Model.html#instance-member-[model_observer]",
    "source/Model.js~Model#[model_observer]",
    "member"
  ],
  [
    "source/model.js~model#constructor",
    "class/source/Model.js~Model.html#instance-constructor-constructor",
    "source/Model.js~Model#constructor",
    "method"
  ],
  [
    "source/model.js~model#foreach",
    "class/source/Model.js~Model.html#instance-method-forEach",
    "source/Model.js~Model#forEach",
    "method"
  ],
  [
    "source/model.js~model#observe",
    "class/source/Model.js~Model.html#instance-method-observe",
    "source/Model.js~Model#observe",
    "method"
  ],
  [
    "source/model.js~model#set",
    "class/source/Model.js~Model.html#instance-method-set",
    "source/Model.js~Model#set",
    "method"
  ],
  [
    "source/model.js~model#unobserve",
    "class/source/Model.js~Model.html#instance-method-unobserve",
    "source/Model.js~Model#unobserve",
    "method"
  ],
  [
    "source/model.js~model#valueof",
    "class/source/Model.js~Model.html#instance-method-valueOf",
    "source/Model.js~Model#valueOf",
    "method"
  ],
  [
    "source/model.js~model.valuechangedhandler",
    "typedef/index.html#static-typedef-ValueChangedHandler",
    "source/Model.js~Model.ValueChangedHandler",
    "typedef"
  ],
  [
    "source/hook/index.js",
    "file/source/hook/index.js.html",
    "source/hook/index.js",
    "file"
  ],
  [
    "source/index.js",
    "file/source/index.js.html",
    "source/index.js",
    "file"
  ],
  [
    "source/scheme/index.js",
    "file/source/scheme/index.js.html",
    "source/scheme/index.js",
    "file"
  ],
  [
    "source/utility/index.js",
    "file/source/utility/index.js.html",
    "source/utility/index.js",
    "file"
  ],
  [
    "source/utility/index.js~decoratordescriptor",
    "typedef/index.html#static-typedef-DecoratorDescriptor",
    "source/utility/index.js~DecoratorDescriptor",
    "typedef"
  ],
  [
    "source/validator.js",
    "file/source/validator.js.html",
    "source/validator.js",
    "file"
  ],
  [
    "source/validator.js~modelvaluehandler",
    "typedef/index.html#static-typedef-ModelValueHandler",
    "source/validator.js~ModelValueHandler",
    "typedef"
  ],
  [
    "test/model.js",
    "test-file/test/Model.js.html",
    "test/Model.js",
    "testFile"
  ],
  [
    "test/scheme.js",
    "test-file/test/scheme.js.html",
    "test/scheme.js",
    "testFile"
  ],
  [
    "test/source/server.js",
    "test-file/test/source/Server.js.html",
    "test/source/Server.js",
    "testFile"
  ],
  [
    "test/source/user.js",
    "test-file/test/source/User.js.html",
    "test/source/User.js",
    "testFile"
  ],
  [
    "test/source/hook.js",
    "test-file/test/source/hook.js.html",
    "test/source/hook.js",
    "testFile"
  ]
]